---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gomod"
    directory: "/plugins/rqlite"
    schedule:
      interval: "weekly"
    groups:
      security:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gomod"
    directory: "/plugins/sqlite"
    schedule:
      interval: "weekly"
    groups:
      security:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "gomod"
    directory: "/plugins/cassandra"
    schedule:
      interval: "weekly"
    groups:
      security:
        update-types:
          - "patch"
          - "minor"
