# Copy schemahero into a thin image
FROM debian:buster
WORKDIR /

RUN apt-get update \
 && apt-get -y install \
    ca-certificates

ADD ./bin/manager /manager

RUN useradd -c 'schemahero user' -m -d /home/schemahero -s /bin/bash -u 1001 schemahero
USER 1001
ENV HOME /home/schemahero

ENTRYPOINT ["/manager", "run"]
