# Build the manager binary
FROM golang:1.12 as builder

# Copy in the go src
WORKDIR /go/src/github.com/schemahero/schemahero
COPY pkg/    pkg/
COPY cmd/    cmd/
COPY go.mod  ./
COPY go.sum ./
COPY Makefile ./

ENV GO111MODULE=on

# Build
RUN make bin/manager

# Copy the controller-manager into a thin image
FROM ubuntu:latest
WORKDIR /
COPY --from=builder /go/src/github.com/schemahero/schemahero/bin/manager .
ENTRYPOINT ["/manager"]
