package database

import (
	"errors"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"

	schemasv1alpha2 "github.com/schemahero/schemahero/pkg/apis/schemas/v1alpha2"
	"github.com/schemahero/schemahero/pkg/database/mysql"
	"github.com/schemahero/schemahero/pkg/database/postgres"
	"github.com/spf13/viper"
	"gopkg.in/yaml.v2"
)

type Database struct {
	Viper *viper.Viper
}

func NewDatabase() *Database {
	return &Database{
		Viper: viper.GetViper(),
	}
}

func (d *Database) CreateFixturesSync() error {
	fmt.Printf("generating fixtures for resources in %s\n", d.Viper.GetString("input-dir"))

	statements := []string{}
	handleFile := func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		fileData, err := ioutil.ReadFile(filepath.Join(d.Viper.GetString("input-dir"), info.Name()))
		if err != nil {
			return err
		}

		var spec *schemasv1alpha2.TableSpec

		parsedK8sObject := schemasv1alpha2.Table{}
		if err := yaml.Unmarshal(fileData, &parsedK8sObject); err == nil {
			if parsedK8sObject.Spec.Schema != nil {
				spec = &parsedK8sObject.Spec
			}
		}

		if spec == nil {
			plainSpec := schemasv1alpha2.TableSpec{}
			if err := yaml.Unmarshal(fileData, &plainSpec); err != nil {
				return err
			}

			spec = &plainSpec
		}

		if spec.Schema == nil {
			fmt.Printf("skipping file %s because there is no schema\n", info.Name())
			return nil
		}

		if d.Viper.GetString("driver") == "postgres" {
			if spec.Schema.Postgres == nil {
				fmt.Printf("skipping file %s because there is no postgres spec\n", info.Name())
			}

			statement, err := postgres.CreateTableStatement(spec.Name, spec.Schema.Postgres)
			if err != nil {
				return err
			}

			statements = append(statements, statement)
		} else if d.Viper.GetString("driver") == "mysql" {
			if spec.Schema.Mysql == nil {
				fmt.Printf("skipping file %s because there is no mysql spec\n", info.Name())
			}

			statement, err := mysql.CreateTableStatement(spec.Name, spec.Schema.Mysql)
			if err != nil {
				return err
			}

			statements = append(statements, statement)
		}

		return nil
	}

	err := filepath.Walk(d.Viper.GetString("input-dir"), handleFile)
	if err != nil {
		fmt.Printf("%#v\n", err)
		return err
	}

	output := strings.Join(statements, ";\n")
	output = fmt.Sprintf("/* Auto generated file. Do not edit by hand. This file was generated by SchemaHero. */\n\n %s;\n\n", output)

	if _, err := os.Stat(d.Viper.GetString("output-dir")); os.IsNotExist(err) {
		os.MkdirAll(d.Viper.GetString("output-dir"), 0755)
	}

	err = ioutil.WriteFile(filepath.Join(d.Viper.GetString("output-dir"), "fixtures.sql"), []byte(output), 0644)
	if err != nil {
		fmt.Printf("%#v\n", err)
		return err
	}

	return nil
}

func (d *Database) ApplySync() error {
	specContents, err := ioutil.ReadFile(d.Viper.GetString("spec-file"))
	if err != nil {
		return err
	}

	var tableSpec schemasv1alpha2.TableSpec
	if err := yaml.Unmarshal(specContents, &tableSpec); err != nil {
		return err
	}

	if d.Viper.GetString("driver") == "postgres" {
		return postgres.DeployPostgresTable(d.Viper.GetString("uri"), tableSpec.Name, tableSpec.Schema.Postgres)
	} else if d.Viper.GetString("driver") == "mysql" {
		return mysql.DeployMysqlTable(d.Viper.GetString("uri"), tableSpec.Name, tableSpec.Schema.Mysql)
	}

	return errors.New("unknown database driver")
}
