/*
Copyright 2021 The SchemaHero Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha4 "github.com/schemahero/schemahero/pkg/apis/schemas/v1alpha4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeViews implements ViewInterface
type FakeViews struct {
	Fake *FakeSchemasV1alpha4
	ns   string
}

var viewsResource = schema.GroupVersionResource{Group: "schemas.schemahero.io", Version: "v1alpha4", Resource: "views"}

var viewsKind = schema.GroupVersionKind{Group: "schemas.schemahero.io", Version: "v1alpha4", Kind: "View"}

// Get takes name of the view, and returns the corresponding view object, and an error if there is any.
func (c *FakeViews) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.View, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(viewsResource, c.ns, name), &v1alpha4.View{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.View), err
}

// List takes label and field selectors, and returns the list of Views that match those selectors.
func (c *FakeViews) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.ViewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(viewsResource, viewsKind, c.ns, opts), &v1alpha4.ViewList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha4.ViewList{ListMeta: obj.(*v1alpha4.ViewList).ListMeta}
	for _, item := range obj.(*v1alpha4.ViewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested views.
func (c *FakeViews) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(viewsResource, c.ns, opts))

}

// Create takes the representation of a view and creates it.  Returns the server's representation of the view, and an error, if there is any.
func (c *FakeViews) Create(ctx context.Context, view *v1alpha4.View, opts v1.CreateOptions) (result *v1alpha4.View, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(viewsResource, c.ns, view), &v1alpha4.View{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.View), err
}

// Update takes the representation of a view and updates it. Returns the server's representation of the view, and an error, if there is any.
func (c *FakeViews) Update(ctx context.Context, view *v1alpha4.View, opts v1.UpdateOptions) (result *v1alpha4.View, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(viewsResource, c.ns, view), &v1alpha4.View{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.View), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeViews) UpdateStatus(ctx context.Context, view *v1alpha4.View, opts v1.UpdateOptions) (*v1alpha4.View, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(viewsResource, "status", c.ns, view), &v1alpha4.View{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.View), err
}

// Delete takes name of the view and deletes it. Returns an error if one occurs.
func (c *FakeViews) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(viewsResource, c.ns, name, opts), &v1alpha4.View{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeViews) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(viewsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha4.ViewList{})
	return err
}

// Patch applies the patch and returns the patched view.
func (c *FakeViews) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.View, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(viewsResource, c.ns, name, pt, data, subresources...), &v1alpha4.View{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.View), err
}
