/*
Copyright 2021 The SchemaHero Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha4

import (
	"context"
	"time"

	v1alpha4 "github.com/schemahero/schemahero/pkg/apis/schemas/v1alpha4"
	scheme "github.com/schemahero/schemahero/pkg/client/schemaheroclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DataTypesGetter has a method to return a DataTypeInterface.
// A group's client should implement this interface.
type DataTypesGetter interface {
	DataTypes(namespace string) DataTypeInterface
}

// DataTypeInterface has methods to work with DataType resources.
type DataTypeInterface interface {
	Create(ctx context.Context, dataType *v1alpha4.DataType, opts v1.CreateOptions) (*v1alpha4.DataType, error)
	Update(ctx context.Context, dataType *v1alpha4.DataType, opts v1.UpdateOptions) (*v1alpha4.DataType, error)
	UpdateStatus(ctx context.Context, dataType *v1alpha4.DataType, opts v1.UpdateOptions) (*v1alpha4.DataType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha4.DataType, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha4.DataTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.DataType, err error)
	DataTypeExpansion
}

// dataTypes implements DataTypeInterface
type dataTypes struct {
	client rest.Interface
	ns     string
}

// newDataTypes returns a DataTypes
func newDataTypes(c *SchemasV1alpha4Client, namespace string) *dataTypes {
	return &dataTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dataType, and returns the corresponding dataType object, and an error if there is any.
func (c *dataTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.DataType, err error) {
	result = &v1alpha4.DataType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datatypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DataTypes that match those selectors.
func (c *dataTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.DataTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha4.DataTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datatypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dataTypes.
func (c *dataTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datatypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dataType and creates it.  Returns the server's representation of the dataType, and an error, if there is any.
func (c *dataTypes) Create(ctx context.Context, dataType *v1alpha4.DataType, opts v1.CreateOptions) (result *v1alpha4.DataType, err error) {
	result = &v1alpha4.DataType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datatypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dataType and updates it. Returns the server's representation of the dataType, and an error, if there is any.
func (c *dataTypes) Update(ctx context.Context, dataType *v1alpha4.DataType, opts v1.UpdateOptions) (result *v1alpha4.DataType, err error) {
	result = &v1alpha4.DataType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datatypes").
		Name(dataType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataType).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dataTypes) UpdateStatus(ctx context.Context, dataType *v1alpha4.DataType, opts v1.UpdateOptions) (result *v1alpha4.DataType, err error) {
	result = &v1alpha4.DataType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datatypes").
		Name(dataType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dataType and deletes it. Returns an error if one occurs.
func (c *dataTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datatypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dataTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datatypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dataType.
func (c *dataTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.DataType, err error) {
	result = &v1alpha4.DataType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datatypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
