/*
Copyright 2021 The SchemaHero Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha4

import (
	"context"
	"time"

	v1alpha4 "github.com/schemahero/schemahero/pkg/apis/schemas/v1alpha4"
	scheme "github.com/schemahero/schemahero/pkg/client/schemaheroclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ViewsGetter has a method to return a ViewInterface.
// A group's client should implement this interface.
type ViewsGetter interface {
	Views(namespace string) ViewInterface
}

// ViewInterface has methods to work with View resources.
type ViewInterface interface {
	Create(ctx context.Context, view *v1alpha4.View, opts v1.CreateOptions) (*v1alpha4.View, error)
	Update(ctx context.Context, view *v1alpha4.View, opts v1.UpdateOptions) (*v1alpha4.View, error)
	UpdateStatus(ctx context.Context, view *v1alpha4.View, opts v1.UpdateOptions) (*v1alpha4.View, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha4.View, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha4.ViewList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.View, err error)
	ViewExpansion
}

// views implements ViewInterface
type views struct {
	client rest.Interface
	ns     string
}

// newViews returns a Views
func newViews(c *SchemasV1alpha4Client, namespace string) *views {
	return &views{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the view, and returns the corresponding view object, and an error if there is any.
func (c *views) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.View, err error) {
	result = &v1alpha4.View{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("views").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Views that match those selectors.
func (c *views) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.ViewList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha4.ViewList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("views").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested views.
func (c *views) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("views").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a view and creates it.  Returns the server's representation of the view, and an error, if there is any.
func (c *views) Create(ctx context.Context, view *v1alpha4.View, opts v1.CreateOptions) (result *v1alpha4.View, err error) {
	result = &v1alpha4.View{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("views").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(view).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a view and updates it. Returns the server's representation of the view, and an error, if there is any.
func (c *views) Update(ctx context.Context, view *v1alpha4.View, opts v1.UpdateOptions) (result *v1alpha4.View, err error) {
	result = &v1alpha4.View{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("views").
		Name(view.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(view).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *views) UpdateStatus(ctx context.Context, view *v1alpha4.View, opts v1.UpdateOptions) (result *v1alpha4.View, err error) {
	result = &v1alpha4.View{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("views").
		Name(view.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(view).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the view and deletes it. Returns an error if one occurs.
func (c *views) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("views").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *views) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("views").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched view.
func (c *views) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.View, err error) {
	result = &v1alpha4.View{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("views").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
