/*
Copyright 2021 The SchemaHero Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha4 "github.com/schemahero/schemahero/pkg/apis/schemas/v1alpha4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataMigrations implements DataMigrationInterface
type FakeDataMigrations struct {
	Fake *FakeSchemasV1alpha4
	ns   string
}

var datamigrationsResource = v1alpha4.SchemeGroupVersion.WithResource("datamigrations")

var datamigrationsKind = v1alpha4.SchemeGroupVersion.WithKind("DataMigration")

// Get takes name of the dataMigration, and returns the corresponding dataMigration object, and an error if there is any.
func (c *FakeDataMigrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.DataMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datamigrationsResource, c.ns, name), &v1alpha4.DataMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.DataMigration), err
}

// List takes label and field selectors, and returns the list of DataMigrations that match those selectors.
func (c *FakeDataMigrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.DataMigrationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datamigrationsResource, datamigrationsKind, c.ns, opts), &v1alpha4.DataMigrationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha4.DataMigrationList{ListMeta: obj.(*v1alpha4.DataMigrationList).ListMeta}
	for _, item := range obj.(*v1alpha4.DataMigrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataMigrations.
func (c *FakeDataMigrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datamigrationsResource, c.ns, opts))

}

// Create takes the representation of a dataMigration and creates it.  Returns the server's representation of the dataMigration, and an error, if there is any.
func (c *FakeDataMigrations) Create(ctx context.Context, dataMigration *v1alpha4.DataMigration, opts v1.CreateOptions) (result *v1alpha4.DataMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datamigrationsResource, c.ns, dataMigration), &v1alpha4.DataMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.DataMigration), err
}

// Update takes the representation of a dataMigration and updates it. Returns the server's representation of the dataMigration, and an error, if there is any.
func (c *FakeDataMigrations) Update(ctx context.Context, dataMigration *v1alpha4.DataMigration, opts v1.UpdateOptions) (result *v1alpha4.DataMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datamigrationsResource, c.ns, dataMigration), &v1alpha4.DataMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.DataMigration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataMigrations) UpdateStatus(ctx context.Context, dataMigration *v1alpha4.DataMigration, opts v1.UpdateOptions) (*v1alpha4.DataMigration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(datamigrationsResource, "status", c.ns, dataMigration), &v1alpha4.DataMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.DataMigration), err
}

// Delete takes name of the dataMigration and deletes it. Returns an error if one occurs.
func (c *FakeDataMigrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(datamigrationsResource, c.ns, name, opts), &v1alpha4.DataMigration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataMigrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datamigrationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha4.DataMigrationList{})
	return err
}

// Patch applies the patch and returns the patched dataMigration.
func (c *FakeDataMigrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.DataMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datamigrationsResource, c.ns, name, pt, data, subresources...), &v1alpha4.DataMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.DataMigration), err
}
