# Note, changes to this file requires manual intervention
# from a maintainer due to security constraints.

steps:
  - label: build
    commands:
      - make
    plugins:
      - docker#v3.2.0:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          mount-checkout: true
          workdir: /go/src/github.com/schemahero/schemahero

  - wait

  - label: integration-tests
    commands:
      - make -C integration run

  - wait

  - commands:
      - bash <(curl -s https://codecov.io/bash)

  - commands:
      - make snapshot-release
    branches: "master"
    plugins:
      - docker#v3.2.0:
          image: replicated/gitops-builder:buildkite-go12-node10
          always-pull: true
          mount-checkout: true
          workdir: /go/src/github.com/schemahero/schemahero
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/var/lib/buildkite-agent/.docker/config.json:/home/builder/.docker/config.json"

  - label: release
    commands:
      - if [ -z "$BUILDKITE_TAG" ]; then echo "Not a tag, not releasing"; else git tag -f "$BUILDKITE_TAG" && make release; fi
    plugins:
      - docker#v3.2.0:
          always-pull: true
          image: replicated/gitops-builder:buildkite-go12-node10
          workdir: /go/src/github.com/schemahero/schemahero
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
          environment:
            - "GITHUB_TOKEN_SCHEMAHERO"
