/*
Copyright 2021 The SchemaHero Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha4

import (
	internalinterfaces "github.com/schemahero/schemahero/pkg/client/schemaheroinformers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DataTypes returns a DataTypeInformer.
	DataTypes() DataTypeInformer
	// Migrations returns a MigrationInformer.
	Migrations() MigrationInformer
	// Tables returns a TableInformer.
	Tables() TableInformer
	// Views returns a ViewInformer.
	Views() ViewInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DataTypes returns a DataTypeInformer.
func (v *version) DataTypes() DataTypeInformer {
	return &dataTypeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Migrations returns a MigrationInformer.
func (v *version) Migrations() MigrationInformer {
	return &migrationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Tables returns a TableInformer.
func (v *version) Tables() TableInformer {
	return &tableInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Views returns a ViewInformer.
func (v *version) Views() ViewInformer {
	return &viewInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
