/*
Copyright 2021 The SchemaHero Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package schemaheroclientset

import (
	"fmt"

	databasesv1alpha4 "github.com/schemahero/schemahero/pkg/client/schemaheroclientset/typed/databases/v1alpha4"
	schemasv1alpha4 "github.com/schemahero/schemahero/pkg/client/schemaheroclientset/typed/schemas/v1alpha4"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	DatabasesV1alpha4() databasesv1alpha4.DatabasesV1alpha4Interface
	SchemasV1alpha4() schemasv1alpha4.SchemasV1alpha4Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	databasesV1alpha4 *databasesv1alpha4.DatabasesV1alpha4Client
	schemasV1alpha4   *schemasv1alpha4.SchemasV1alpha4Client
}

// DatabasesV1alpha4 retrieves the DatabasesV1alpha4Client
func (c *Clientset) DatabasesV1alpha4() databasesv1alpha4.DatabasesV1alpha4Interface {
	return c.databasesV1alpha4
}

// SchemasV1alpha4 retrieves the SchemasV1alpha4Client
func (c *Clientset) SchemasV1alpha4() schemasv1alpha4.SchemasV1alpha4Interface {
	return c.schemasV1alpha4
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		if configShallowCopy.Burst <= 0 {
			return nil, fmt.Errorf("burst is required to be greater than 0 when RateLimiter is not set and QPS is set to greater than 0")
		}
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.databasesV1alpha4, err = databasesv1alpha4.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.schemasV1alpha4, err = schemasv1alpha4.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.databasesV1alpha4 = databasesv1alpha4.NewForConfigOrDie(c)
	cs.schemasV1alpha4 = schemasv1alpha4.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.databasesV1alpha4 = databasesv1alpha4.New(c)
	cs.schemasV1alpha4 = schemasv1alpha4.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
