apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: airport
  namespace: schemahero-e2e
spec:
  database: airlinedb
  name: schemahero-test
  schema:
    postgres:
      columns:
        - name: id
          type: integer
        - name: name
          type: text
---
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: airport
  namespace: schemahero-e2e
spec:
  database: airlinedb
  name: schemahero-test2
  schema:
    postgres:
      primaryKey: [id]
      columns:
        - name: id
          type: integer
        - name: name
          type: text
        - name: city
          type: text