apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: flight-status
spec:
  database: airlinedb
  name: flight_status
  schema:
    timescaledb:
      hypertable:
        timeColumnName: time
        chunkTimeInterval: "1 day"
        retention:
          interval: "30 days"
      columns:
        - name: time
          type: timestamp without time zone
          constraints:
            notNull: true
        - name: flight_number
          type: varchar (40)
        - name: status
          type: varchar(40)

