apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: controller-manager-service
  namespace: schemahero-system
spec:
  ports:
  - port: 443
    targetPort: 9876
  selector:
    control-plane: schemahero
status:
  loadBalancer: {}
