/*
Copyright 2019 Replicated, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha3

import (
	scheme "pkg/client/schemaheroclientset/scheme"
	"time"

	v1alpha3 "github.com/schemahero/schemahero/pkg/apis/schemas/v1alpha3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TablesGetter has a method to return a TableInterface.
// A group's client should implement this interface.
type TablesGetter interface {
	Tables(namespace string) TableInterface
}

// TableInterface has methods to work with Table resources.
type TableInterface interface {
	Create(*v1alpha3.Table) (*v1alpha3.Table, error)
	Update(*v1alpha3.Table) (*v1alpha3.Table, error)
	UpdateStatus(*v1alpha3.Table) (*v1alpha3.Table, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha3.Table, error)
	List(opts v1.ListOptions) (*v1alpha3.TableList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.Table, err error)
	TableExpansion
}

// tables implements TableInterface
type tables struct {
	client rest.Interface
	ns     string
}

// newTables returns a Tables
func newTables(c *SchemasV1alpha3Client, namespace string) *tables {
	return &tables{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the table, and returns the corresponding table object, and an error if there is any.
func (c *tables) Get(name string, options v1.GetOptions) (result *v1alpha3.Table, err error) {
	result = &v1alpha3.Table{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tables").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Tables that match those selectors.
func (c *tables) List(opts v1.ListOptions) (result *v1alpha3.TableList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha3.TableList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tables.
func (c *tables) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a table and creates it.  Returns the server's representation of the table, and an error, if there is any.
func (c *tables) Create(table *v1alpha3.Table) (result *v1alpha3.Table, err error) {
	result = &v1alpha3.Table{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tables").
		Body(table).
		Do().
		Into(result)
	return
}

// Update takes the representation of a table and updates it. Returns the server's representation of the table, and an error, if there is any.
func (c *tables) Update(table *v1alpha3.Table) (result *v1alpha3.Table, err error) {
	result = &v1alpha3.Table{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tables").
		Name(table.Name).
		Body(table).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *tables) UpdateStatus(table *v1alpha3.Table) (result *v1alpha3.Table, err error) {
	result = &v1alpha3.Table{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tables").
		Name(table.Name).
		SubResource("status").
		Body(table).
		Do().
		Into(result)
	return
}

// Delete takes name of the table and deletes it. Returns an error if one occurs.
func (c *tables) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tables").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tables) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tables").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched table.
func (c *tables) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha3.Table, err error) {
	result = &v1alpha3.Table{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tables").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
